const defaultLayout = <String, dynamic>{
  "font": "auto",
  "subFont": "same",
  "weight": 700,
  "subWeight": 500,
  "italic": false,
  "subItalic": false,
  "lineHeight": 1.4,
  "subGap": 0.3,
  "autoFit": true,
  "anchor": "mc",
  "marginX": 32,
  "marginY": 28,
  "stroke2Width": 0,
  "stroke2Color": "#ffffff",
  "gradientThird": false,
  "gradientColor3": "#ff8a00",
  "gradientDirection": "vertical",
  "shadowColor": "#000000",
  "shadowOpacity": 0.53,
  "shadowBlur": 8,
  "shadowX": 0,
  "shadowY": 3,
  "glowStrength": 1,
  "glitchColor": "#ff285a",
  "glitchColor2": "#28e6ff",
  "cursorColor": "#ffffff",
};
const defaultMotion = <String, dynamic>{
  "enabled": false,
  "inStagger": 0.1,
  "outStagger": 0,
  "outOrder": "forward",
  "inEase": "auto",
  "outEase": "auto",
  "inDirection": "left",
  "outDirection": "left",
  "inPower": 1,
  "outPower": 1,
  "holdPower": 1,
  "outEnabled": true,
  "subMotion": "same",
  "subDelay": -0.2,
  "startDelay": 0.1,
  "endDelay": 0.3,
};
const defaultSequence = <String, dynamic>{
  "mode": "message",
  "reveal": "char",
  "wrapChars": 0,
  "pageSplit": true,
  "cps": 12,
  "glyphDuration": 0.4,
  "punctPause": 0.25,
  "linePause": 0.35,
  "lineInterval": 0.9,
  "sweepDuration": 1.2,
  "pageGap": 0.3,
  "cursor": false,
  "scrollSpeed": 90,
  "scrollFade": true,
  "soloSize": 0.55,
  "soloPause": 0.4,
  "soloImpact": 1,
  "spreadHold": 0.5,
  "spreadDuration": 0.9,
};
const defaultBackdrop = <String, dynamic>{
  "type": "none",
  "color": "#000000",
  "opacity": 0.45,
  "sync": true,
};
